name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kuqi666
          outputs: dist/github-contribution-grid-snake.svg

      - name: Generate Snake SVG (Dark Theme)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kuqi666
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
